import { Invoice } from './types';

export const initialInvoices: Invoice[] = [
  {
    id: 'INV-2048',
    buyerName: 'Nexus Retail Group',
    buyerEmail: 'ap@nexusretail.com',
    buyerCompany: 'Nexus Retail Group',
    amount: 12800,
    dueDate: '2026-03-29',
    description: 'Bulk apparel shipment for spring season rollout',
    status: 'Pending',
    financingStatus: 'Requested',
    lineItems: [
      { id: 'LI-1', title: 'Premium Cotton Shirts', quantity: 160, unitPrice: 45 },
      { id: 'LI-2', title: 'Freight and Handling', quantity: 1, unitPrice: 5600 },
    ],
    createdAt: '2026-03-09',
  },
  {
    id: 'INV-2041',
    buyerName: 'Apex Imports Ltd.',
    buyerEmail: 'finance@apeximports.com',
    buyerCompany: 'Apex Imports Ltd.',
    amount: 24550,
    dueDate: '2026-03-14',
    description: 'Electronics components procurement order',
    status: 'Overdue',
    financingStatus: 'Not Requested',
    lineItems: [
      { id: 'LI-1', title: 'Microcontroller Units', quantity: 500, unitPrice: 32.5 },
      { id: 'LI-2', title: 'Power Adapters', quantity: 250, unitPrice: 18.2 },
      { id: 'LI-3', title: 'Insurance', quantity: 1, unitPrice: 3800 },
    ],
    createdAt: '2026-02-25',
  },
  {
    id: 'INV-2039',
    buyerName: 'BlueHarbor Foods',
    buyerEmail: 'ops@blueharborfoods.com',
    buyerCompany: 'BlueHarbor Foods',
    amount: 9340,
    dueDate: '2026-03-10',
    description: 'Cold chain packaging supply contract',
    status: 'Paid',
    financingStatus: 'Not Requested',
    lineItems: [
      { id: 'LI-1', title: 'Insulated Containers', quantity: 340, unitPrice: 21 },
      { id: 'LI-2', title: 'Protective Inserts', quantity: 340, unitPrice: 6.5 },
    ],
    createdAt: '2026-02-20',
  },
  {
    id: 'INV-2035',
    buyerName: 'Zenith Construction',
    buyerEmail: 'treasury@zenithbuild.com',
    buyerCompany: 'Zenith Construction',
    amount: 31200,
    dueDate: '2026-04-06',
    description: 'Structural steel and fabrication materials',
    status: 'Financed',
    financingStatus: 'Approved',
    lineItems: [
      { id: 'LI-1', title: 'Steel Beams', quantity: 120, unitPrice: 180 },
      { id: 'LI-2', title: 'Custom Fabrication', quantity: 1, unitPrice: 9600 },
    ],
    createdAt: '2026-03-01',
  },
];
